//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppG4
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string Manv { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<double> hsl { get; set; }
        public string madv { get; set; }
    
        public virtual Donvi Donvi { get; set; }
    }
}
